### ISSUE TITLE
Error reading Swagger

### ISSUE THREAD

**Issue by waytoharish** [swagger-api/swagger-js#1021]
Hi,
I have attached Swagger file but swagger-client never able to parse it always giving error even though swagger is valid one.
My code in nodeJS is-
```js
var SwaggerClient = require('swagger-client');
  var spec=require('./test.yaml');
  var client = new SwaggerClient({
  spec: spec,
  success: function() {
   console.log(">>>>>>>>>>>>");
 }
});
```

[test.zip](https://github.com/swagger-api/swagger-js/files/940717/test.zip)

**Comment by webron** [comment]
Which version of swagger-js do you use? What's the error you're getting?

**Comment by waytoharish** [comment]
I am using swagger-client. 

    at phaseInvoke (c:\Harish\Strongloop\PromiseTest\SubscriptionWithPromise\node_modules\strong-remoting\lib\remote-objects.js:649:9)
    at runHandler (c:\Harish\Strongloop\PromiseTest\SubscriptionWithPromise\node_modules\strong-remoting\node_modules\loopback-phase\lib\phase.js:135:5)
    at iterate (c:\Harish\Strongloop\PromiseTest\SubscriptionWithPromise\node_modules\strong-remoting\node_modules\loopback-phase\node_modules\async\lib\async.js:146:13)
    at Object.async.eachSeries (c:\Harish\Strongloop\PromiseTest\SubscriptionWithPromise\node_modules\strong-remoting\node_modules\loopback-phase\node_modules\async\lib\async.js:162:9)
should be valid true

**Comment by webron** [comment]
That's not the version of the project..

**Comment by waytoharish** [comment]
swagger-client@3.0.6

**Comment by webron** [comment]
Thanks. Can you share the spec you're trying to load?

**Comment by waytoharish** [comment]
Swagger is added with name of test.zip

**Comment by webron** [comment]
@waytoharish - thanks.

@buunguyen - any thoughts?

**Comment by waytoharish** [comment]
Hi,
Any update regarding this ???

**Comment by buunguyen** [comment]
I'm not a YAML expert, but should the 1.0.0 be in quote?

Also, the right way to use the new client is `Swagger().then(...)`, not passing in callback.

**Comment by webron** [comment]
`1.0.0` is not a number, so it doesn't need to be quoted. 

`1.0` would be treated as a number unless quoted.

**Comment by buunguyen** [comment]
Right.

This is not valid: `require('./test.yaml')`.  You can't "require" YAML in Node.
