### ISSUE TITLE
v3.3.0 broke g11n-pipeline

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-js#1171]
v3.2.2 worked, v3.3.0 did not.  Didn't finish git bisect yet. I worked around this for now in https://github.com/IBM-Bluemix/gp-js-client/issues/104 by pinning to `swagger-client@3.2.x`

The callsite in question is https://github.com/IBM-Bluemix/gp-js-client/blob/3eea05dacef3f7358d4732bf5334cb7a0c3c2b81/lib/client.js#L109

and in summary: 

```
/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(e){function t(n){if(r[n])return r[n].exports;var a=r[n]={i:n,l:!1,exports:{}};return e[n].call(a.exports,a,a.exports,t),a.l=!0,a.exports}var r={};return t.m=e,t.c=r,t.i=function(e){return e},t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:n})},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=53)}([function(e,t){e.exports=require("babel-runtime/core-js/object/keys")},function(e,t){e.exports=require("babel-runtime/core-js/object/assign")},function(e,t){e.exports=require("babel-runtime/helpers/typeof")},function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function a(e){var t=e.openapi;return!!t&&(0,k.default)(t,"3")}function u(e){var t=e.swagger;

TypeError: Cannot read property 'content-type' of undefined
    at a (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:3864)
    at /Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:27329
    at Function.o [as resolve] (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:28249)
    at a.resolve (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:12954)
    at a (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:12126)
    at Client.createSwaggerClient (/Users/srl/src/gp-js-client/lib/client.js:109:27)
    at new Client (/Users/srl/src/gp-js-client/lib/client.js:74:21)
…
```

**Comment by srl295** [comment]
Is there a way to get an _unminified_ `dist/index.js`? I tried a bit, but my webpack-fu is not all that.

**Comment by srl295** [comment]
bisect points at 060b7913ac0e3e16dbc812459ee8e15bb07ce9be

**Comment by srl295** [comment]
To turn off minification, remove `-p` from the `npm run build` script args to webpack.

{{{
/Users/srl/src/swagger-js/dist/index.js:474
  var contentType = request.headers['content-type'] || request.headers['Content-Type'];
                                   ^

TypeError: Cannot read property 'content-type' of undefined
    at http (/Users/srl/src/swagger-js/dist/index.js:474:36)
    at /Users/srl/src/swagger-js/dist/index.js:2500:12
    at Function.resolve (/Users/srl/src/swagger-js/dist/index.js:2546:117)
    at Swagger.resolve (/Users/srl/src/swagger-js/dist/index.js:1276:20)
    at Swagger (/Users/srl/src/swagger-js/dist/index.js:1246:19)
    at Client.createSwaggerClient (/Users/srl/src/gp-js-client/lib/client.js:109:27)
    at new Client (/Users/srl/src/gp-js-client/lib/client.js:74:21)
}}}

**Comment by srl295** [comment]
My bug, please see https://github.com/IBM-Bluemix/gp-js-client/pull/106
