### ISSUE TITLE
Client errs trying to get statusText of undefined when using https against http server

### ISSUE THREAD

**Issue by matthewadams** [swagger-api/swagger-js#1288]
If you change the `schemes` value in swagger 2.0 document to be `schemes: ['https']` but the server only is listening via http, the client errs with the following:
```
     TypeError: Cannot read property 'statusText' of undefined
      at _callee$ (src/http.js:49:33)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
      at <anonymous>
```

**Comment by matthewadams** [comment]
Reproducible test case can be found at https://github.com/matthewadams/swagger-js/blob/1288/test/client.js#L216

**Comment by shockey** [comment]
thanks for the test case, @matthewadams - looks like it passed without any changes, but the test will make sure it stays that way! 😄
