### ISSUE TITLE
swagger-client 3.8.7: Cannot find module 'babel-runtime/helpers/extends'

### ISSUE THREAD

**Issue by kevinoid** [swagger-api/swagger-js#1335]
### Q&A (please complete the following information)
 - OS: Linux
 - Environment: Node v8.11.2
 - Method of installation: npm
 - Swagger-Client version: 3.8.7
 - Swagger/OpenAPI version: Any

### Describe the bug you're encountering

Loading the `swagger-client` module throws an exception.

### To reproduce

Steps to reproduce the behavior, run the following commands:
```sh
cd "$(mktemp -d)"
npm install swagger-client
node -e 'require("swagger-client")'
```
The last command will print the following output:

    module.js:549
        throw err;
        ^
    
    Error: Cannot find module 'babel-runtime/helpers/extends'
        at Function.Module._resolveFilename (module.js:547:15)
        at Function.Module._load (module.js:474:25)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.module.exports.Object.defineProperty.value (/tmp/tmp.xKaTQzrxLn/node_modules/swagger-client/dist/index.js:1:777)
        at t (/tmp/tmp.xKaTQzrxLn/node_modules/swagger-client/dist/index.js:1:177)
        at Object.<anonymous> (/tmp/tmp.xKaTQzrxLn/node_modules/swagger-client/dist/index.js:1:16367)
        at t (/tmp/tmp.xKaTQzrxLn/node_modules/swagger-client/dist/index.js:1:177)
        at Object.module.exports.Object.defineProperty.value (/tmp/tmp.xKaTQzrxLn/node_modules/swagger-client/dist/index.js:1:15912)
        at t (/tmp/tmp.xKaTQzrxLn/node_modules/swagger-client/dist/index.js:1:177)

### Expected behavior
The `swagger-client` module can be loaded without throwing an exception.

**Comment by shockey** [comment]
Acknowledged - sorry for the issue here @kevinoid!

As a stopgap, I'm going to publish a patch (`v3.8.8`) that adds `babel-runtime` back to `dependencies`.

**Comment by shockey** [comment]
`v3.8.8` is now available, which should mitigate the issue for now.

Not sure where this is coming from just by looking at the stack trace, but I'll dig into it in the coming week.

I'm also going to look into setting up some tests that simulate an npm consumer of the package - this is the second dependency-related regression we've had in as many months, so we clearly need a safeguard.

**Comment by kevinoid** [comment]
`v3.8.8` works for me.  Thanks @shockey!

**Comment by shockey** [comment]
Closing; the current version now fails builds if a dependency is missing:

```
  2:1  error  'babel-runtime' should be listed in the project's dependencies. Run 'npm i -S babel-runtime' to add it  import/no-extraneous-dependencies
```
