### ISSUE TITLE
Regression: Use of parameters causes "ReferenceError: navigator is not defined"

### ISSUE THREAD

**Issue by kevinoid** [swagger-api/swagger-js#1382]
### Q&A (please complete the following information)
 - OS: Debian GNU/Linux
 - Environment: Node.js v8.11.2
 - Method of installation: npm
 - Swagger-Client version: 3.8.16 - 3.8.19
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering
Calling an operation with a parameter value causes the returned `Promise` to be rejected with `ReferenceError: navigator is not defined`.

### To reproduce...

Run the following commands:
```sh
cd "$(mktemp -d)"
npm init -y
npm install swagger-client
edit index.js
node index.js
```
Where `index.js` is edited to contain the following content:
```js
const SwaggerClient = require('swagger-client');
new SwaggerClient({
  spec: {
    swagger: '2.0',
    info: {
      title: 'Example API',
      version: '0.0.1'
    },
    host: 'example.com',
    schemes: [
      'https'
    ],
    paths: {
      '/example': {
        get: {
          operationId: 'getExample',
          parameters: [
            {
              name: 'param1',
              in: 'query',
              type: 'string'
            }
          ],
          responses: {
            200: {
              description: 'Success',
              schema: {}
            }
          }
        }
      }
    }
  }
})
  .then((client) => client.apis.default.getExample({param1: 'value1'}))
  .catch(console.error);
```
It will output something similar to the following:

    ReferenceError: navigator is not defined
        at i (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:5016)
        at s (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:5476)
        at /tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:6030
        at Array.reduce (<anonymous>)
        at l (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:5839)
        at c (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:6866)
        at Object.u [as buildRequest] (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:39415)
        at Function.a [as execute] (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:37213)
        at a.execute (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:17318)
        at Object.getExample (/tmp/tmp.laZz1j7yQQ/node_modules/swagger-client/dist/index.js:1:35213)

### Expected behavior

The returned `Promise` would be rejected with `Error: Not Found` (or resolved with a valid response when using a valid host+path).

### Additional context or thoughts

The error is resolved by reverting f9689ac4f0bcfb0ad5eb6767c3c144a819fe1019.

**Comment by shockey** [comment]
Confirmed!

**Comment by shockey** [comment]
@kevinoid, `v3.8.20` [has been released](https://www.npmjs.com/package/swagger-client) with a fix (#1383) for this!

Please let me know if this doesn't resolve your issue.

**Comment by kevinoid** [comment]
I can confirm the issue is fixed for me.  Thanks @shockey!
