### ISSUE TITLE
Build error when import Swagger from 'swagger-client'

### ISSUE THREAD

**Issue by fix-me** [swagger-api/swagger-js#1391]
Hi,

I just wanted to start with the swagger-client from scratch,
but unfortunately importing it broke the build process already.

My steps were the following:
I set up a simple and general purpose boilerplate with `create-react-library`
and installed the swagger client with the command `npm i swagger-client`.
After that I just placed the line `import Swagger from 'swagger-client';` in the library **'src/index.js'** and ran `npm start`. Boom, compile error.

Do you have any suggestion? What am I missing?

Thank you very much for investigation!

@ref: https://github.com/transitive-bullshit/create-react-library/issues/78#issue-366862537

**Comment by shockey** [comment]
@fix-me, can you share the error you're seeing?

**Comment by fix-me** [comment]
Sure, and thanks for your fast reply - I didn't expect it 👍 
I will even share my codebase, so you may doublecheck it.

https://github.com/fix-me/swagger-library-test

One thing is strange, because when I ran the start script for the first time I got a different error.
As far as I can remember it was something with one of those big arrays as gbChars etc.

First I will attach the console output, then the debug log file:

**console**

```
C:\test\swagger-library-test>npm start

> swagger-library-test@1.0.0 start C:\test\swagger-library-test
> rollup -c -w
rollup v0.64.1
bundles src/index.js → dist\index.js, dist\index.es.js...
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\test\swagger-library-test\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\test\swagger-library-test\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\test\swagger-library-test\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\test\swagger-library-test\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\test\swagger-library-test\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\test\swagger-library-test\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at 'C:\test\swagger-library-test\node_modules\util\util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
[!] Error: Unexpected token
node_modules\mime-db\db.json (2:40)
1: {
2:   "application/1d-interleaved-parityfec": {
                                           ^
3:     "source": "iana"
4:   },

1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-library-test@1.0.0 start: `rollup -c -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-library-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**debug-log**

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle swagger-library-test@1.0.0~prestart: swagger-library-test@1.0.0
6 info lifecycle swagger-library-test@1.0.0~start: swagger-library-test@1.0.0
7 verbose lifecycle swagger-library-test@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle swagger-library-test@1.0.0~start: PATH: [...]
9 verbose lifecycle swagger-library-test@1.0.0~start: CWD: C:\test\swagger-library-test
10 silly lifecycle swagger-library-test@1.0.0~start: Args: [ '/d /s /c', 'rollup -c -w' ]
11 silly lifecycle swagger-library-test@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle swagger-library-test@1.0.0~start: Failed to exec start script
13 verbose stack Error: swagger-library-test@1.0.0 start: `rollup -c -w`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid swagger-library-test@1.0.0
15 verbose cwd C:\test\swagger-library-test
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error swagger-library-test@1.0.0 start: `rollup -c -w`
22 error Exit status 1
23 error Failed at the swagger-library-test@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

The preferring built-in messages disappear when I set `{ preferBuiltins: false }` in the resolve plugin.

**Comment by char0n** [comment]
This is more issue with rollup configuration rather then issue of how `swagger-client` build artifacts are distributes. In order for rollup build `swagger-client` successfully your rollup configuration needs to change. Attaching a git patch with changes to your repository:
```diff
diff --git a/package.json b/package.json
index 589c288..66038e5 100644
--- a/package.json
+++ b/package.json
@@ -27,6 +27,7 @@
     "react-dom": "^15.0.0 || ^16.0.0"
   },
   "devDependencies": {
+    "@rollup/plugin-json": "^4.1.0",
     "babel-core": "^6.26.3",
     "babel-eslint": "^8.2.5",
     "babel-plugin-external-helpers": "^6.22.0",
@@ -58,6 +59,6 @@
     "dist"
   ],
   "dependencies": {
-    "swagger-client": "^3.8.21"
+    "swagger-client": "^3.10.9"
   }
 }
diff --git a/rollup.config.js b/rollup.config.js
index 826dc00..db727c0 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -4,6 +4,7 @@ import external from 'rollup-plugin-peer-deps-external'
 import postcss from 'rollup-plugin-postcss'
 import resolve from 'rollup-plugin-node-resolve'
 import url from 'rollup-plugin-url'
+import json from '@rollup/plugin-json';

 import pkg from './package.json'

@@ -31,7 +32,10 @@ export default {
       exclude: 'node_modules/**',
       plugins: [ 'external-helpers' ]
     }),
-    resolve(),
-    commonjs()
+    resolve({
+      preferBuiltins: false
+    }),
+    commonjs(),
+    json(),
   ]
 }
```

You need to install rollup `json` plugin a switch `preferBuiltins` to false, as `swagger-client` is an [isomorphic](https://medium.com/capital-one-tech/why-everyone-is-talking-about-isomorphic-universal-javascript-and-why-it-matters-38c07c87905) library.

**Comment by char0n** [comment]
Hope it helps, closing this issue for now.
