### ISSUE TITLE
Swagger Client Initialisation is failing.

### ISSUE THREAD

**Issue by jaliph** [swagger-api/swagger-js#1460]
Getting a sudden error while initialisation of the Swagger.

```
[ TypeError: Cannot read property 'applyPatch' of undefined
      at Object.a [as applyPatch] (/path/to/node_modules/swagger-client/dist/index.js:1:9824)
      at e.value (/path/to/node_modules/swagger-client/dist/index.js:1:24637)
      at /path/to/node_modules/swagger-client/dist/index.js:1:24394
      at Array.forEach (<anonymous>)
      at e.value (/path/to/node_modules/swagger-client/dist/index.js:1:23989)
      at new e (/path/to/node_modules/swagger-client/dist/index.js:1:20400)
      at a (/path/to/node_modules/swagger-client/dist/index.js:1:19328)
      at t (/path/to/node_modules/swagger-client/dist/index.js:1:14280)
      at Function.o [as resolve] (/path/to/node_modules/swagger-client/dist/index.js:1:14995)
      at a.resolve (/path/to/node_modules/swagger-client/dist/index.js:1:18398)
      at new a (/path/to/node_modules/swagger-client/dist/index.js:1:17450)
      at a (/path/to/node_modules/swagger-client/dist/index.js:1:17408)
      at Promise (/path/to/node_modules/connector-compliance-tests/classes/swaggerApiHelper.js:188:7)
      at new WrappedPromise (/path/to/node_modules/async-listener/es6-wrapped-promise.js:13:18)
      at ApiHelper.doClientInitialisation (/path/to/node_modules/connector-compliance-tests/classes/swaggerApiHelper.js:187:12)
      at Promise.all.swaggerObjectList.map (/path/to/node_modules/connector-compliance-tests/validators/swaggerValidator.js:90:31)
      at Array.map (<anonymous>)
      at Promise (/path/to/node_modules/connector-compliance-tests/validators/swaggerValidator.js:88:35)
      at new WrappedPromise (/path/to/node_modules/async-listener/es6-wrapped-promise.js:13:18)
      at Object.setupSwaggerClient (/path/to/node_modules/connector-compliance-tests/validators/swaggerValidator.js:86:10)
      at Context.<anonymous> (/path/to/node_modules/connector-compliance-tests/testSuite/discoverySwaggerSchemaTests.js:43:32)
      at callFnAsync (/path/to/node_modules/mocha/lib/runnable.js:371:21)
      at Test.Runnable.run (/path/to/node_modules/mocha/lib/runnable.js:318:7)
      at Runner.runTest (/path/to/node_modules/mocha/lib/runner.js:443:10)
      at /path/to/node_modules/mocha/lib/runner.js:549:12
      at next (/path/to/node_modules/mocha/lib/runner.js:361:14)
      at /path/to/node_modules/mocha/lib/runner.js:371:7
      at next (/path/to/node_modules/mocha/lib/runner.js:295:14)
      at Immediate._onImmediate (/path/to/node_modules/mocha/lib/runner.js:339:5)
      at processImmediate (internal/timers.js:443:21) ]

```

Swagger Client version 3.9.0

**Comment by olemoign** [comment]
Getting same error here.

**Comment by zyzo** [comment]
Downgrade to `3.5.0` worked for me. 

(I didn't try a more recent version)

**Comment by alecf** [comment]
I also started getting this, after updating some npm packages... not such which one though

**Comment by alecf** [comment]
the problem is version 2.2.0 of `fast-json-patch`!

**Comment by shockey** [comment]
**Confirmed, installing `fast-json-patch@2.2.0` locally is blowing up Swagger Client tests.**

I'm going to dig in a bit before taking action, but I'll most likely push out a new Swagger Client patch version that pins `fast-json-patch@~2.1.0` today.

**Comment by shockey** [comment]
**I've just published `swagger-client@3.9.1` directly on top of 3.9.0** (i.e., this release doesn't include the housekeeping items currently on master). [Diff here](https://github.com/swagger-api/swagger-js/compare/31cb227...shockey:6a504584903e86697dc5f8f696af7dcf63de54bb). This version of Swagger Client is pinned to the tighter range, `fast-json-patch@~2.1.0`, that I mentioned earlier. 

This should solve the issue for now, but I'll file an upstream bug with `fast-json-patch` to let them know it appears an incorrectly-set `__esModule` flag is causing issues.

Thanks for the help here @jaliph @olemoign @alecf!

**Comment by olemoign** [comment]
Man, 100% of the credits to you. :)

**Comment by jaliph** [comment]
@shockey Thanks for the quick resolution

**Comment by shockey** [comment]
FYI, I've opened the upstream issue with `fast-json-patch`: https://github.com/Starcounter-Jack/JSON-Patch/issues/233
