### ISSUE TITLE
 swagger-client@3.22.2: `absolutifyPointer` returns `[ERR_INVALID_URL]: Invalid URL` on Windows

### ISSUE THREAD

**Issue by AlvaroRausell** [swagger-api/swagger-js#3149]
### Q&A (please complete the following information)
 - OS: Windows
 - Environment: Node.js 18
 - Method of installation: npm
 - Swagger-Client version: 3.22.2

### Describe the bug you're encountering

The PR #3148 introduces a bug on Windows, as the returned value for `cwd` has backslashes and [line 82](https://github.com/swagger-api/swagger-js/blob/cd84a30db43c14f4e2f1876465ce0ed2a4d0d9c8/src/specmap/helpers.js#L82) fails with [ERR_INVALID_URL]: Invalid URL. 

### To reproduce...

Run `absolutifyPointer` on Windows, which any parameters.

### Expected behavior
It should return the same path it would on UNIX systems, not give a TypeError.
### Stack trace
```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at Object.resolve (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\@swagger-api\apidom-reference\cjs\util\url.cjs:230:23)
    at absolutifyPointer (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\helpers.js:65:40)
    at Object.plugin (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\lib\refs.js:159:60)
    at traverse (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\index.js:143:35)
    at traverse.next (<anonymous>)
    at traverse (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\index.js:137:26)
    at traverse.next (<anonymous>)
    at traverse (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\index.js:137:26)
    at traverse.next (<anonymous>)
    at traverse (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\index.js:137:26)
    at traverse.next (<anonymous>)
    at traverse (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\index.js:137:26)
    at traverse.next (<anonymous>)
    at traverse (C:\S000\WMB\inst.images\amd64_nt_4\shipdata\server\nodejs_all\node_modules\swagger-client\lib\specmap\index.js:137:26) {
  input: '',
  code: 'ERR_INVALID_URL'
}```

**Comment by char0n** [comment]
Hi @AlvaroRausell,

Thanks for reporting, it seems that this is never ending story. I'll try to address this during tomorrow morning.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-js/pull/3150. 

Given that SwaggerClient can only process HTTP(S) URLs, we can use static `CWD` in form of a constant URL.

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-js/releases/tag/v3.22.3. @AlvaroRausell can you please confirm you're fine? THanks!

**Comment by AlvaroRausell** [comment]
Hi @char0n, all fixed now! Thanks for the quick response

**Comment by char0n** [comment]
Huh, glad to hear that ;]
