### ISSUE TITLE
adding clientAuthorization broken

### ISSUE THREAD

**Issue by MaxPMagee** [swagger-api/swagger-js#401]
The example in readme.md for adding a new authorization token is busted.

Using the boilerplate code plus
`client.clientAuthorizations.add("apiKey", new client.ApiKeyAuthorization("api_key","special-key","query"));`

results in a TypeError:
`client.clientAuthorizations.add("api_key", ...`
`                            ^` (carat under add)
`TypeError: Cannot call method 'add' of undefined`

I got the authorization working using the constructor method listed in Feature request #146, but the readme page still references the old method (that appears to not work anymore).

**Comment by ponelat** [comment]
Thanks for pointing that out.
clientAuthorizations is an instance method of the client (npm: swagger-client, repo: swagger-js)
So we're assuming that 'client' is the instance, not the constructor method - like we have in the README above. Which is confusing :)

**Comment by fehguy** [comment]
this should be fixed now.

**Comment by slidenerd** [comment]
Nope just got this error from the standard sample at Microsoft botframework [HERE](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/core-DirectLine/DirectLineClient/app.js)
```
Error initializing DirectLine client TypeError: Cannot read property 'add' of undefined
    at D:\bots\zupcoin test\twitter\directline_client.js:24:36
    at tryCatcher (D:\bots\zupcoin test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Unhandled rejection TypeError: Cannot read property 'Conversations' of undefined
    at D:\bots\zupcoin test\twitter\directline_client.js:33:11
    at tryCatcher (D:\bots\zupcoin test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\bots\zupcoin test\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\bots\zupcoin test\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```
The client object has no clientauthorization object it seems and therefore throws this error. Any ideas how it can be fixed
```
var directLineClient = rp(directLineSpecUrl)
    .then(function (spec) {
        // client
        return new Swagger({
            spec: JSON.parse(spec.trim()),
            usePromise: true
        });
    })
    .then(function (client) {
        // add authorization header to client
        client.clientAuthorizations.add('AuthorizationBotConnector', new Swagger.ApiKeyAuthorization('Authorization', 'Bearer ' + directLineSecret, 'header'));
        return client;
    })
    .catch(function (err) {
        console.error('Error initializing DirectLine client', err);
    });
```

**Comment by ladenedge** [comment]
@slidenerd: You're probably on an old version.  Check out the [Migration from 2.x instructions](https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md#authorizations).
