### ISSUE TITLE
Pass authorizations to constructor broken?

### ISSUE THREAD

**Issue by indolering** [swagger-api/swagger-js#478]
I've been attempting to pass in authorizations to the constructor, as the [code appears to support this](https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L117):

```
swagger = new client({
  url: 'http://example.tld/spec.json',
  success: init,
  failure: fail,
  authorizations : {
    easyapi_basic: {
    name: "basicAuth",
    username: "username",
    password: "password"
    }
  }
});
```

However, [swagger.apply](https://github.com/swagger-api/swagger-js/blob/master/lib/auth.js#L61) throws the following error:

```
/Users/indolering/easyapi-spec/node_modules/swagger-client/lib/auth.js:61
      status = status || !!auth.apply(obj); // logical ORs regarding status
                                ^
TypeError: undefined is not a function
    at /Users/indolering/easyapi-spec/node_modules/swagger-client/lib/auth.js:61:33
    at module.exports (/Users/indolering/easyapi-spec/node_modules/swagger-client/node_modules/lodash-compat/internal/createBaseFor.js:19:11)
    at baseForOwn (/Users/indolering/easyapi-spec/node_modules/swagger-client/node_modules/lodash-compat/internal/baseForOwn.js:14:10)
    at module.exports (/Users/indolering/easyapi-spec/node_modules/swagger-client/node_modules/lodash-compat/internal/createBaseEach.js:17:14)
    at Object.module.exports [as each] (/Users/indolering/easyapi-spec/node_modules/swagger-client/node_modules/lodash-compat/internal/createForEach.js:16:9)
    at SwaggerAuthorizations.apply (/Users/indolering/easyapi-spec/node_modules/swagger-client/lib/auth.js:59:5)
    at SwaggerClient.build (/Users/indolering/easyapi-spec/node_modules/swagger-client/lib/client.js:205:31)
    at SwaggerClient.initialize (/Users/indolering/easyapi-spec/node_modules/swagger-client/lib/client.js:141:10)
    at new module.exports (/Users/indolering/easyapi-spec/node_modules/swagger-client/lib/client.js:99:17)
    at Object.<anonymous> (/Users/indolering/easyapi-spec/index.js:11:18)
```

What am I doing wrong here?  Is there a special function I should be using to construct the authorizations object?

**Comment by ponelat** [comment]
@indolering I'm afraid that form isn't supported... although perhaps it would be nice to.
Here is an example of how to pass in auth layers to the constructor...

```javascript
var swagger = new client({
  url: 'http://example.com/spec.json',
  success: function() {},
  authorizations : {
    easyapi_basic: new client.PasswordAuthorization('<name>', '<username>', '<password>'),
    someHeaderAuth: new client.ApiKeyAuthorization('<nameOfHeader>', '<value>', 'header'),
    someQueryAuth: new client.ApiKeyAuthorization('<nameOfQueryKey>', '<value>', 'query'),
    someCookieAuth: new client.CookieAuthorization('<cookie>'),
  }
});
```

We're working on making this documentation more accessible.

**Comment by indolering** [comment]
Oh, I misread the `PasswordAuthorization` function as simply returning an object.  This feature isn't worth the effort, just document that construction.

**Comment by webron** [comment]
Fair enough, let's convert it to a documentation thing then. Thanks.

**Comment by fehguy** [comment]
added in the section:  `...or with the swagger-client constructor`

**Comment by indolering** [comment]
I actually ripped this out of my code because it forces an OPTIONS request when fetching the Swagger spec.  This should be added to the documentation.
